// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrtdtqsfyxxahzmvlvjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJydGR0cXNmeXh4YWh6bXZsdmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODMwNDUsImV4cCI6MjA3MDg1OTA0NX0.1yp5WtliN7vUkvqz0jS9Y5rFEwMUn-eHiti6vyTILgI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});